version: '3.8'

services:
  mongodb:
    image: mongo:6.0.18
    container_name: mongodb
    restart: on-failure
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - graylog

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    container_name: opensearch
    restart: on-failure
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - action.auto_create_index=false
      - plugins.security.ssl.http.enabled=false
      - plugins.security.disabled=true
      # Troque a senha abaixo por uma segura
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=superSenhaComplexa123!
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - graylog

  graylog:
    # Versão Community do Graylog
    image: graylog/graylog:6.1
    container_name: graylog
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_started
      opensearch:
        condition: service_started
    entrypoint: >
      /usr/bin/tini -- wait-for-it opensearch:9200 --
      /docker-entrypoint.sh
    environment:
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_PASSWORD_SECRET: "muitoseguraepepper1234567890"
      # Usuario e senha definidos no .env
      GRAYLOG_ROOT_USERNAME: "${GRAYLOG_ROOT_USERNAME}"
      # Coloque o SHA2 da senha do admin:
      # unix: echo -n "${GRAYLOG_ROOT_PASSWORD_SHA2}" | sha256sum | cut -d " " -f1
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2}"
      GRAYLOG_REPORT_DISABLE_SANDBOX: "true"
    ports:
      - "9000:9000"
      - "1514:1514"
      - "1514:1514/udp"
      - "12201:12201"
      - "12201:12201/udp"
    volumes:
      - graylog_journal:/usr/share/graylog/data
    networks:
      - graylog

  analises_logs:
    build: .
    container_name: analises_logs
    restart: on-failure
    env_file:
      - .env
    depends_on:
      opensearch:
        condition: service_started
      mongodb:
        condition: service_started
    volumes:
      - .:/app
    networks:
      - graylog

networks:
  graylog:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config:
  opensearch_data:
  graylog_journal:
